import {
  TelegramIcon,
  DiscordIcon,
  GithubIcon,
  LinkedInIcon,
  InstagramIcon,
  PatreonIcon,
  WhatsappIcon,
  EmailIcon,
} from "./../../components/icons";

export const socialMedia = [
  {
    name: "Instagram",
    link: "https://www.instagram.com/mr.nicolasfrazao/",
    icon: InstagramIcon,
  },
  {
    name: "Github",
    link: "https://github.com/nicolasfrazao",
    icon: GithubIcon,
  },
  {
    name: "Patreon",
    link: "https://patreon.com/NFDev",
    icon: PatreonIcon,
  },
  {
    name: "Discord",
    link: "https://discord.gg/rtkH6d22",
    icon: DiscordIcon,
  },
  {
    name: "Telegram",
    link: "https://t.me/mrnmfz",
    icon: TelegramIcon,
  },
  {
    name: "Linkedin",
    link: "https://www.linkedin.com/in/nicolasfrazao/",
    icon: LinkedInIcon,
  },
  {
    name: "Whatsapp",
    link: "+55996912133",
    icon: WhatsappIcon,
  },
];

export const links = [
  {
    name: "Home",
    link: "/",
  },
  {
    name: "About me",
    link: "/about",
  },
  {
    name: "Projects",
    link: "/projects",
  },
  {
    name: "Contact",
    link: "/contact",
  },
  {
    name: "My History",
    link: "/history",
  },
  {
    name: "Why Hire Me",
    link: "/why-hire-me",
  },
  {
    name: "My Skills",
    link: "/skills",
  },
  {
    name: "My Experience",
    link: "/experience",
  },
  {
    name: "My Education",
    link: "/education",
  },
  {
    name: "My Certificates",
    link: "/certificates",
  },
  {
    name: "My Interests",
    link: "/interests",
  },
];

export const myHistory = [
  {
    title: "My History",
    description:
      "My history is a collection of my life experiences and achievements.",
    content: "",
    link: "/history",
  },
  {
    title: "Why Hire Me",
    description:
      "Why hire me is a collection of my why hire me experiences and achievements.",
    content: "",
    link: "/why-hire-me",
  },
  {
    title: "My Skills",
    description: "My skills is a collection of my skills and achievements.",
    content: "",
    link: "/skills",
  },
  {
    title: "My Experience",
    description:
      "My experience is a collection of my experience and achievements.",
    content: "",
    link: "/experience",
  },
  {
    title: "My Education",
    description:
      "My education is a collection of my education and achievements.",
    content: "",
    link: "/education",
  },
  {
    title: "My Certificates",
    description:
      "My certificates is a collection of my certificates and achievements.",
    content: "",
    link: "/certificates",
  },
  {
    title: "My Interests",
    description:
      "My interests is a collection of my interests and achievements.",
    content: "",
    link: "/interests",
  },
];

export const interests = [
  "Sports",
  "Music",
  "Travel",
  "Reading",
  "Cooking",
  "Gaming",
  "Photography",
  "Hiking",
  "Swimming",
  "F1",
  "Basketball",
  "Soccer",
  "Engineering",
  "Programming",
  "Motorsports",
  "Driving",
  "Learning",
  "Technology",
  "Space",
  "Science",
  "History",
  "Philosophy",
  "Psychology",
  "Art",
  "Design",
  "Food",
  "Nature",
  "Animals",
  "Pets",
  "Fitness",
];

export const certifications = {
  computerScience: [
    "CS50's Computer Science",
    "StanfordOnline: Computer Science 101",
    "HarvardX: CS50's AP® Computer Science",
    "StanfordOnline: Algorithms: Design and Analysis",
    "GTx: Data Structures & Algorithms",
    "IBM: Data Structures & Algorithms Using C++",
    "ColumbiaX: Programming & Data Structures",
    "UC3Mx: Introduction to Java Programming: Fundamental Data Structures and Algorithms",
  ],
  cloudComputing: [
    "Cloud Application Development",
    "Full Stack Cloud Developer",
    "Microsoft Azure Fundamentals",
    "AWS Technical Essentials",
    "Solutions Architect",
    "Application Architect",
    "Cloud Engineer",
    "Cloud DevOps Engineer",
    "IBM Cloud Essentials",
    "GoogleCloud: Google Cloud Computing Foundations: Cloud Computing Fundamentals",
    "GoogleCloud: Google Cloud Big Data and Machine Learning Fundamentals",
    "GoogleCloud: Google Cloud Fundamentals: Core Infrastructure",
    "AI: Cloud Computing Foundations",
    "AI: Cloud Virtualization, Containers and APIs",
    "UMGC, USMx: Cloud Computing Infrastructure",
  ],
  cybersecurity: [
    "IBM: Cybersecurity Basics",
    "IBM: Beginners Guide to Cybersecurity",
    "USMx, UMBC: Cybersecurity Essentials",
    "RITx: Cybersecurity Fundamentals",
    "KULeuvenX: Web Security Fundamentals",
    "Linuxfoundationx: Secure Software Development: Requirements, Design, and Reuse",
  ],
  dataScienceAndAI: [
    "IBM: Introduction to Data Science",
    "Introduction to Machine Learning and AI",
    "IBM: Introduction to Generative AI",
    "IBM: Data Science Tools",
    "IBM: SQL for Data Science",
    "AI: Generative AI and LLMs on AWS",
    "AI: Open Source LLMOps",
    "UMontrealX: Deep Learning Essentials",
    "IBM: Deep Learning with Python and PyTorch",
    "RWTHx: Basics of Machine Learning",
    "IBM: PyTorch Basics for Machine Learning",
    "AI: Virtualization, Docker, and Kubernetes for Data Engineering",
  ],
  programmingLanguages: [
    "Python Programming: Basic Skills",
    "Codio: C++ Programming: Basic Skills",
    "IBM: Fundamentals of C++",
    "Codio: C++ Programming: Object-Oriented Design",
    "DartmouthX, IMTx: C Programming: Pointers and Memory Management",
    "C Programming: Getting Started",
    "TUMx: Software Engineering Essentials",
    "IBM: Object Oriented Implementation Using C++",
  ],
  blockchainAndWeb3: [
    "Web3x: Introduction to Blockchain and Web3",
    "IBM: Introduction to Blockchain",
    "BerkeleyX: Bitcoin and Cryptocurrencies",
    "BerkeleyX: Blockchain Technology",
    "HKUx: Blockchain and FinTech: Basics, Applications, and Limitations",
  ],
  devOpsAndSoftwareEngineering: [
    "IBM: DevOps Basics for Everyone",
    "IBM: Git and GitHub Basics",
    "IBM: Introduction to Cloud Native, DevOps, Agile, and NoSQL",
    "IBM: Software, Programming, and Database Basics",
    "IBM: DevOps and Software Engineering",
    "AWS: DevOps on AWS: Code, Build, and Test",
    "AI: DevOps, DataOps, MLOps",
    "ibm: Continuous Integration and Delivery (CI/CD)",
    "IBM: Operating Systems and Security",
    "IBM: Introduction to Containers, Kubernetes and OpenShift",
    "LinuxFoundationX: Introduction to Kubernetes",
    "AWS: Hands-on with AWS: Software Development Practices",
    "IBM: Back-end Application Development with Node.js and Express",
  ],
  electronicsAndEngineering: [
    "MITx: Circuits and Electronics",
    "NUS: Circuits for Beginners",
    "MITx: Supply Chain Fundamentals",
    "MITx: Introduction to Aerodynamics",
    "MITx: Supply Chain Dynamics",
    "MathWorks: Introduction to Engineering Design",
    "NUS: Semiconductors",
    "ChalmersX: Electric and Conventional Vehicles",
    "AdelaideX: Introduction to Project Management",
    "ChalmersX: Hybrid Vehicles",
    "DelftX: Electric Cars",
    "DelftX: Understanding Nuclear Energy",
  ],
  businessAndFinance: [
    "Entrepreneurial Mindset and Leadership",
    "MITx: Becoming an Entrepreneur",
    "IIMBx: Accounting and Finance",
    "Digital Marketing Strategy",
    "Online Advertising & Social Media",
    "IIMBx: Strategic Management",
    "ColumbiaX: Introduction to Corporate Finance",
    "BabsonX: The Entrepreneurial Mindset",
    "BerkleeX: Creativity & Entrepreneurship",
    "USMx, UMD: Creating Innovative Business Models",
  ],
};
export const skills = {
  programming: [
    "JavaScript",
    "Python",
    "Java",
    "C++",
    "C#",
    "TypeScript",
    "SQL",
    "NoSQL",
  ],
  webDevelopment: [
    "React",
    "Next.js",
    "Node.js",
    "HTML",
    "CSS",
    "Tailwind CSS",
    "Bootstrap",
    "GraphQL",
    "Express.js",
  ],
  devOps: [
    "Docker",
    "Kubernetes",
    "AWS",
    "Azure",
    "Git",
    "CI/CD",
    "Jenkins",
    "Terraform",
    "Ansible",
  ],
  machineLearning: [
    "TensorFlow",
    "PyTorch",
    "OpenCV",
    "NumPy",
    "Natural Language Processing (NLP)",
  ],
  blockchain: [
    "Ethereum",
    "Web3.js",
    "Cryptography",
    "DeFi Protocols",
    "Blockchain Architecture",
  ],
  cloudComputing: [
    "AWS Lambda",
    "Google Cloud Platform",
    "Microsoft Azure",
    "Serverless Architecture",
    "Cloud Security",
    "CloudFormation",
  ],
  business: [
    "Project Management",
    "Business Strategy",
    "Data Analysis",
    "Financial Modeling",
    "Market Research",
    "Digital Marketing",
    "Entrepreneurship",
  ],
  softwareEngineering: [
    "System Design",
    "Design Patterns",
    "Agile Methodologies",
    "Software Testing",
    "Version Control",
    "Microservices Architecture",
  ],
  electronicsAndEngineering: [
    "Embedded Systems",
    "Digital Circuit Design",
    "Microcontrollers",
    "Power Electronics",
    "Control Systems",
    "Signal Processing",
  ],
};
